alter table cinnost drop foreign key fk_uzivatel_id_0;
alter table kalendar drop foreign key fk_kalendar_definice_id;
alter table kalendar drop foreign key fk_uzivatel_id_1;
alter table kalendar_cinnost drop foreign key fk_cinnost_id;
alter table kalendar_cinnost drop foreign key fk_uzivatel_id_2;
alter table kalendar_cinnost drop foreign key fk_pracovni_pomer_id;
alter table kalendar_cinnost drop foreign key fk_kalendar_id;
alter table kalendar_definice drop foreign key fk_uzivatel_id_3;
alter table nastaveni_systemu drop foreign key fk_uzivatel_id_4;
alter table pracovni_pomer drop foreign key fk_uzivatel_id_5;
alter table sablona_vykaz drop foreign key fk_uzivatel_id_6;
alter table svatek drop foreign key fk_uzivatel_id_7;
alter table tb_pracovni_pomer_sablona_vykaz drop foreign key fk_sablona_vykaz_pracovni_pomer;
alter table tb_pracovni_pomer_sablona_vykaz drop foreign key fk_sablona_vykaz_id;
drop table if exists cinnost;
drop table if exists kalendar;
drop table if exists kalendar_cinnost;
drop table if exists kalendar_definice;
drop table if exists nastaveni_systemu;
drop table if exists pracovni_pomer;
drop table if exists sablona_vykaz;
drop table if exists svatek;
drop table if exists systemova_informace;
drop table if exists tb_pracovni_pomer_sablona_vykaz;
drop table if exists uzivatel;
create table cinnost (cinnost_id bigint not null auto_increment, uzivatel_id bigint, kod varchar(10) not null, nazev varchar(128) not null, primary key (cinnost_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
create table kalendar (kalendar_id bigint not null auto_increment, datum_importu datetime not null, kalendar_definice_id bigint, uzivatel_id bigint, primary key (kalendar_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
create table kalendar_cinnost (kalendar_cinnost_id bigint not null auto_increment, datum datetime not null, pocet_hodin double precision not null, cinnost_id bigint, pracovni_pomer_id bigint, uzivatel_id bigint, kalendar_id bigint, cas_od datetime not null, cas_do datetime not null, primary key (kalendar_cinnost_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
create table kalendar_definice (kalendar_definice_id bigint not null auto_increment, kod varchar(10) not null, nazev varchar(64) not null, tag_pracovni_pomer varchar(32) not null, tag_kalendar_cinnost varchar(32) not null, uzivatel_id bigint, primary key (kalendar_definice_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
create table nastaveni_systemu (nastaveni_systemu_id bigint not null auto_increment, nazev varchar(128) not null, hodnota varchar(128) not null, uzivatel_id bigint, primary key (nastaveni_systemu_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
create table pracovni_pomer (pracovni_pomer_id bigint not null auto_increment, kod varchar(10) not null, nazev varchar(128) not null, velikost_uvazku double precision not null, uzivatel_id bigint, primary key (pracovni_pomer_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
create table sablona_vykaz (sablona_vykaz_id bigint not null auto_increment, kod varchar(10) not null, nazev varchar(64) not null, typ integer not null, data blob not null, uzivatel_id bigint, primary key (sablona_vykaz_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
create table svatek (svatek_id bigint not null auto_increment, datum datetime not null, nazev varchar(64) not null, uzivatel_id bigint, kod varchar(10) not null, primary key (svatek_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
create table systemova_informace (systemova_informace_id bigint not null auto_increment, datum datetime not null, nadpis varchar(64) not null, data text not null, primary key (systemova_informace_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
create table tb_pracovni_pomer_sablona_vykaz (pracovni_pomer_id bigint not null, sablona_vykaz_id bigint not null, primary key (pracovni_pomer_id, sablona_vykaz_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
create table uzivatel (uzivatel_id bigint not null auto_increment, jmeno varchar(32) not null, prijmeni varchar(64) not null, titul_pred varchar(32), titul_za varchar(32), login varchar(32) not null, heslo varchar(64), primary key (uzivatel_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
alter table cinnost add index fk_uzivatel_id (uzivatel_id), add constraint fk_uzivatel_id_0 foreign key (uzivatel_id) references uzivatel (uzivatel_id);
alter table kalendar add index fk_kalendar_definice_id (kalendar_definice_id), add constraint fk_kalendar_definice_id foreign key (kalendar_definice_id) references kalendar_definice (kalendar_definice_id);
alter table kalendar add index fk_uzivatel_id (uzivatel_id), add constraint fk_uzivatel_id_1 foreign key (uzivatel_id) references uzivatel (uzivatel_id);
alter table kalendar_cinnost add index fk_cinnost_id (cinnost_id), add constraint fk_cinnost_id foreign key (cinnost_id) references cinnost (cinnost_id);
alter table kalendar_cinnost add index fk_uzivatel_id (uzivatel_id), add constraint fk_uzivatel_id_2 foreign key (uzivatel_id) references uzivatel (uzivatel_id);
alter table kalendar_cinnost add index fk_pracovni_pomer_id (pracovni_pomer_id), add constraint fk_pracovni_pomer_id foreign key (pracovni_pomer_id) references pracovni_pomer (pracovni_pomer_id);
alter table kalendar_cinnost add index fk_kalendar_id (kalendar_id), add constraint fk_kalendar_id foreign key (kalendar_id) references kalendar (kalendar_id);
alter table kalendar_definice add index fk_uzivatel_id (uzivatel_id), add constraint fk_uzivatel_id_3 foreign key (uzivatel_id) references uzivatel (uzivatel_id);
alter table nastaveni_systemu add index fk_uzivatel_id (uzivatel_id), add constraint fk_uzivatel_id_4 foreign key (uzivatel_id) references uzivatel (uzivatel_id);
alter table pracovni_pomer add index fk_uzivatel_id (uzivatel_id), add constraint fk_uzivatel_id_5 foreign key (uzivatel_id) references uzivatel (uzivatel_id);
alter table sablona_vykaz add index fk_uzivatel_id (uzivatel_id), add constraint fk_uzivatel_id_6 foreign key (uzivatel_id) references uzivatel (uzivatel_id);
alter table svatek add index fk_uzivatel_id (uzivatel_id), add constraint fk_uzivatel_id_7 foreign key (uzivatel_id) references uzivatel (uzivatel_id);
alter table tb_pracovni_pomer_sablona_vykaz add index fk_sablona_vykaz_pracovni_pomer (pracovni_pomer_id), add constraint fk_sablona_vykaz_pracovni_pomer foreign key (pracovni_pomer_id) references pracovni_pomer (pracovni_pomer_id);
alter table tb_pracovni_pomer_sablona_vykaz add index fk_sablona_vykaz_id (sablona_vykaz_id), add constraint fk_sablona_vykaz_id foreign key (sablona_vykaz_id) references sablona_vykaz (sablona_vykaz_id);
